language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="libgtk-3-dev libpolkit-agent-1-dev libpolkit-gobject-1-dev meson valac"

install:
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && ninja -C build"

script:
 - echo BUILDS PASSED
